In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import sys
sys.path.insert(0, '/home/tomek/ib_tools/')
from indicators import get_signals

In [2]:
data = pd.read_pickle('freeze/freeze_df_NQZ9.pickle')

In [3]:
data.head(40)

,backfill,open,high,low,close,price,volume,ema_fast,atr,signal
date,,,,,,,,,,
2018-02-01 04:48:00,True,6980.0,6988.0,6964.0,6987.0,6978.559502,14920,6978.559502,24.000000,0.0
2018-02-01 11:34:00,True,6987.0,7011.0,6962.0,6973.0,6975.138629,14963,6976.834812,36.656250,0.0
2018-02-01 14:12:00,True,6972.0,6973.0,6947.0,6955.0,6957.368682,15001,6970.237659,33.014999,0.0
2018-02-01 14:44:00,True,6955.0,6955.0,6928.0,6929.0,6938.128569,15382,6962.008599,31.454395,0.0
2018-02-01 15:02:00,True,6929.0,6933.0,6904.0,6916.0,6915.561298,15111,6952.406932,30.938669,0.0
2018-02-01 15:27:00,True,6916.0,6918.0,6898.0,6913.0,6907.656372,15055,6944.634314,28.999739,0.0
2018-02-01 15:33:00,True,6913.0,6933.0,6910.0,6933.0,6922.999773,16067,6941.387005,28.077028,0.0
2018-02-01 15:39:00,True,6933.0,6946.0,6930.0,6941.0,6939.452989,15096,6941.130918,26.432049,0.0
2018-02-01 15:48:00,True,6941.0,6943.0,6923.0,6928.0,6932.019692,16758,6940.049768,25.643853,0.0
2018-02-01 15:57:00,True,6928.0,6954.0,6925.0,6954.0,6942.382900,15655,6940.300965,26.018466,0.0
2018-02-01 16:08:00,True,6954.0,6960.0,6946.0,6951.0,6953.644268,14956,6941.617583,24.784254,0.0
2018-02-01 16:24:00,True,6951.0,6963.0,6948.0,6954.0,6954.059740,15195,6942.752089,23.852184,0.0
2018-02-01 16:37:00,True,6954.0,6961.0,6940.0,6960.0,6948.783734,15525,6943.263864,23.598389,0.0
2018-02-01 16:53:00,True,6960.0,6972.0,6958.0,6966.0,6963.963065,15586,6944.907840,22.795892,0.0
2018-02-01 17:08:00,True,6966.0,6973.0,6955.0,6958.0,6964.507471,15282,6946.372376,22.417229,0.0
2018-02-01 17:27:00,True,6958.0,6963.0,6949.0,6951.0,6955.247919,15078,6946.999108,21.786848,0.0
2018-02-01 17:46:00,True,6951.0,6970.0,6949.0,6969.0,6958.698540,15344,6947.782856,21.730736,0.0
2018-02-01 18:18:00,True,6969.0,6973.0,6958.0,6964.0,6964.795249,14964,6948.867774,21.272135,0.0
2018-02-01 18:55:00,True,6964.0,6970.0,6961.0,6966.0,6965.893849,15084,6949.904582,20.470782,0.0
2018-02-01 19:36:00,True,6966.0,6980.0,6965.0,6968.0,6973.299353,15081,6951.268694,20.127488,0.0
2018-02-01 19:57:00,True,6968.0,6969.0,6941.0,6943.0,6953.689520,15188,6951.404187,20.603380,0.0
2018-02-01 20:10:00,True,6943.0,6948.0,6933.0,6939.0,6940.862119,15222,6950.836537,20.276351,0.0
2018-02-01 20:23:00,True,6939.0,6939.0,6914.0,6920.0,6926.591868,17146,6949.578017,20.543056,0.0
2018-02-01 20:38:00,True,6920.0,6932.0,6919.0,6928.0,6925.527120,15273,6948.372217,20.130277,0.0
2018-02-01 21:01:00,True,6928.0,6943.0,6925.0,6942.0,6935.884165,15579,6947.766481,20.017100,0.0
2018-02-01 21:28:00,True,6942.0,6943.0,6918.0,6919.0,6932.231152,15742,6947.036285,20.274510,0.0
2018-02-01 21:36:00,True,6919.0,6921.0,6893.0,6897.0,6904.536338,17640,6945.097764,20.663118,-1.0
2018-02-01 21:45:00,True,6897.0,6900.0,6885.0,6897.0,6891.820163,15584,6942.736327,20.385365,-1.0
2018-02-01 21:56:00,True,6897.0,6920.0,6897.0,6910.0,6910.305771,15423,6941.337771,20.510553,0.0
2018-02-01 22:02:00,True,6909.0,6930.0,6905.0,6925.0,6914.295363,15975,6940.201790,20.720636,0.0
2018-02-01 22:31:00,True,6925.0,6928.0,6890.0,6911.0,6905.278156,15671,6938.771187,21.511734,0.0
2018-02-02 00:39:00,True,6911.0,6964.0,6898.0,6951.0,6935.599816,14942,6938.644375,23.506461,0.0
2018-02-02 04:05:00,True,6950.0,6956.0,6913.0,6938.0,6934.639440,14939,6938.487901,24.363235,0.0
2018-02-02 09:33:00,True,6938.0,6944.0,6914.0,6914.0,6929.152197,14987,6938.131195,24.606299,0.0
2018-02-02 11:05:00,True,6914.0,6918.0,6866.0,6872.0,6888.256829,14974,6936.265988,25.766172,-1.0
2018-02-02 12:41:00,True,6872.0,6875.0,6848.0,6849.0,6864.948698,14935,6933.653380,25.817507,-1.0
2018-02-02 14:02:00,True,6849.0,6888.0,6845.0,6887.0,6864.483224,15211,6931.169370,26.520519,-1.0
2018-02-02 14:39:00,True,6887.0,6887.0,6856.0,6863.0,6868.787337,14918,6928.971728,26.700869,0.0
2018-02-02 15:03:00,True,6863.0,6893.0,6862.0,6870.0,6878.344860,14972,6927.220945,26.871303,0.0
2018-02-02 15:30:00,True,6870.0,6883.0,6863.0,6883.0,6874.262908,15486,6925.422022,26.602911,0.0

In [4]:
df = pd.DataFrame(data[['open', 'close']])
df['volume_weighted'] = (df.close + df.open)/2 * df.volume
weighted_price = df.volume_weighted.sum() / df.volume.sum()

AttributeError: 'DataFrame' object has no attribute 'volume'

In [ ]:
periods = [10, 20, 40, 80, ]

In [ ]:
min_max = pd.DataFrame({'close': data.price})

In [ ]:
min_max

In [ ]:
for p in periods:
    min_max[f'min_{p}'] = min_max.close.rolling(p).min()
    #min_max[f'max_{p}'] = min_max.close.rolling(p).max()

In [ ]:
min_max.plot(figsize=(18, 9), grid=True);

In [ ]:
data[data['signal'] != 0].loc['20190927':].head(50)

In [ ]:
data[data['signal'] != 0].tail(60)

In [ ]:
averages = pd.DataFrame({'price': data.price,
                       'ema_fast': data.price.ewm(span=100).mean(),
                       'ema_slow': data.price.ewm(span=160).mean()})

In [ ]:
averages.plot(figsize=(18,9), grid=True);